<?php

namespace SiteBundle\Entity\Repository;

/**
 * EntradaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntradaRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodos($limite = null){
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->addOrderBy('e.filial', 'ASC')
                ->addOrderBy('e.dataCadastro', 'DESC');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function listarTodosPorFilial($filial){
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->innerJoin('SiteBundle:Filial', 'f', 'WITH', 'e.filial = f.id')
                ->distinct()
                ->where('f.slug = :filial')
                ->setParameter('filial', $filial)
                ->addOrderBy('e.dataCadastro', 'DESC');
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function listarTodosParaVotacao(){
        $qb = $this->createQueryBuilder('e')
                ->select('e')
                ->distinct()
                ->andWhere('e.escolhida = 1')
                ->andWhere('e.ativo = 1')
                ->addOrderBy('e.dataCadastro', 'DESC');
        
        return $qb->getQuery()->getResult();
        
    }
    
}
