<?php

namespace SiteBundle\Entity\Repository;

/**
 * FilialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FilialRepository extends \Doctrine\ORM\EntityRepository
{
}
