<?php

namespace SiteBundle\Entity\Repository;

/**
 * FraseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FraseRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function listarTodos($limite = null){
        $qb = $this->createQueryBuilder('f')
                ->select('f.id, f.frase, f.autor, fi.nome AS filial, COUNT(v.id) AS votos')
                ->innerJoin('SiteBundle:Voto', 'v', 'WITH', 'v.frase = f.id')
                ->innerJoin('SiteBundle:Filial', 'fi', 'WITH', 'f.filial = fi.id')
                ->distinct()
                ->groupBy('f')
                ->addOrderBy('f.autor', 'ASC');
        
        if(false == is_null($limite)){
            $qb->setMaxResults($limite);
        }
        
        return $qb->getQuery()->getResult();
        
    }
    
}
