<?php

namespace SiteBundle\Entity\Repository;

/**
 * VotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VotoRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function checarVotoUsuario($usuario){
        $qb = $this->createQueryBuilder('v')
                ->select('v')
                ->innerJoin('SiteBundle:Entrada', 'e', 'WITH', 'v.entrada = e.id')
                ->innerJoin('SiteBundle:Usuario', 'u', 'WITH', 'v.usuario = u.id')
                ->distinct()
                ->where('u.id = :usuario')
                ->setParameter('usuario', $usuario)
                ->addOrderBy('e.dataCadastro', 'DESC');
        
        return $qb->getQuery()->getResult();
        
    }
    
    public function listarTodosPorFrase($frase){
        $qb = $this->createQueryBuilder('v')
                ->select('v')
                ->distinct()
                ->where('v.frase = :frase')
                ->setParameter('frase', $frase)
                ->addOrderBy('v.dataCadastro', 'ASC');

        return $qb->getQuery()->getResult();
        
    }
    
    public function listarTodosAgrupadoPorFrase(){
        $qb = $this->createQueryBuilder('v')
                ->select('v')
                ->innerJoin('SiteBundle:Frase', 'f', 'WITH', 'v.frase = f.id')
                ->distinct()
                ->addOrderBy('f.autor', 'ASC');

        return $qb->getQuery()->getResult();
        
    }
    
}
