site_homepage:
    path:     /
    defaults: { _controller: SiteBundle:Page:index }
    
site_voto:
    path:     /voto
    defaults: { _controller: SiteBundle:Page:voto }
    
site_admin_homepage:
    path:     /admin
    defaults: { _controller: SiteBundle:Admin:index }
    
site_admin_filial_homepage:
    path:     /admin/{filial}/home
    defaults: { _controller: SiteBundle:Admin:indexFilial, filial: '' }
    
site_admin_carrega_votos:
    path:     /carrega_votos/{frase}
    defaults: { _controller: SiteBundle:Admin:carregaVotos, frase: '' }
    
site_admin_lista_corrida:
    path:     /lista-corrida
    defaults: { _controller: SiteBundle:Admin:listaCorrida }

site_processa_formulario:
    path:     /processa-form
    defaults: { _controller: SiteBundle:Page:processaForm }
    
site_processa_voto:
    path:     /processa-voto
    defaults: { _controller: SiteBundle:Page:processaVoto }
    
google_login:
    path: /login/check-google